FROM ubuntu:24.04

# Install required tools
RUN apt-get update && apt-get install -y time
RUN apt-get install -y netcat-openbsd



# Set working directory
WORKDIR /app

# Everything else will come from your volume mount at runtime
# COPY evaluation/scripts/rpc_host_wrapper.sh /usr/local/bin/rpc_host_wrapper.sh
# RUN chmod +x /usr/local/bin/rpc_host_wrapper.sh
